---
title: "dashboardProjectDays3"
author: "Luis P. Prieto"
date: "8 de enero de 2018"
output: 
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(Hmisc)
library(knitr)
library(gsheet)
library(data.table)
library(ggplot2)
library(ineq)
library("FactoMineR")
library("factoextra")
library(lubridate)
library(mgcv)

#library(syuzhet)
#library(tm)
#library(wordcloud)
#library(SnowballC)
#library(stringi)
#library(stringr)

knitr::opts_chunk$set(echo = FALSE)

# Observations spreadsheet # 10.01
# url_obs <- "https://docs.google.com/spreadsheets/d/1hkkeSRYKKtlpxYAA4jEUddhkv-X5oj6gXzGPKobA5Wc/edit"
# Observations spreadsheet # 15.01
url_obs <- "https://docs.google.com/spreadsheets/d/15nRUUpDSBWBUDgXDDizf6Ij50fLlDDp1f3xj_kRbLP0/edit"


# Student feedback spreadsheet # 10.01
# url_quest <- "https://docs.google.com/spreadsheets/d/1o-JBf9MeReo8ob8LT80OfE3_ZQwFG5Xi9AJtRkxSRUc/edit"
# Student feedback spreadsheet # 15.01
url_quest <- "https://docs.google.com/spreadsheets/d/11cDBX25XCJq89UdmWydXEfMvdHcA4xG-jhbSBgxEnQw/edit"

# Does todays observer questionnaire have the question about obs.id?
obscol=F

pollSpreadsheet <- function(url, namesCol=NULL, factors=NULL){
  data <- reactivePoll(5000, session,
                     readLastTimestamp <- function(){
                        # We read the latest response timestamp
                        data <- as.data.frame(gsheet2tbl(url))
                        if(nrow(data)>0 & ncol(data)>1){
                          data[nrow(data),1]
                        }else{
                          ""
                        }
                      },
                     readValue <- function(){
                        data <- as.data.frame(gsheet2tbl(url))
                        #We clean it up a bit
                        if(!is.null(namesCol) & length(namesCol)>0){
                          names(data) <- namesCol 
                        }
                        if(!is.null(factors) & length(factors)>0){
                          for(f in factors){
                            data[,f] <- as.factor(data[,f])
                          }  
                        }
                        data
                      })
  data
}


ObsData <- pollSpreadsheet(url_obs, 
                          c("timestamp","group","activity",
                            "StudentA","StudentB","StudentC",
                            "StudentD","StudentE","comment"))#,"observer"))

ObD <- reactive({
  d <- ObsData()
  d
})

QueData <- pollSpreadsheet(url_quest, 
                          c("timestamp","group","student","activity","contribution",
                            "difficulty","preparedness","satisfaction","relevance",
                            "collab.challenges","skill.gaps")) #TODO: put column names

QuD <- reactive({
  data <- QueData()
  data
})


processObservationData <- function(data, 
                                   nrlevels=6, 
                                   date=as.POSIXct(strptime("10-01-2018", "%d-%m-%Y")),
                                   project="Isle", 
                                   activitycol=T,
                                   observercol=T){
  
  obs_data <- data
  
  #Clean up empty columns
  # for(i in ncol(obs_data):1){
  #   if(sum(complete.cases(obs_data[i]))==0 || sum(obs_data[i]!="")==0 || sum(obs_data[i]!="")==1) obs_data <- obs_data[,-i]
  # }
  
  # Cleanup invalid data, before 10am like "2017-10-11 09:44:49 GMT"
  #obs_data <- obs_data[obs_data$timestamp>as.POSIXct("2017-10-11 10:00:00 GMT", origin = "1970-01-01", tz = "GMT"),]
  
  # Student view of the observations
  if(observercol){
    if(!activitycol){
      student_obs <- melt(obs_data, id=c(1:2,ncol(obs_data)), measure=3:(ncol(obs_data)-2))
      names(student_obs)[[4]]<-"student"
    }else{
      student_obs <- melt(obs_data, id=c(1:3,ncol(obs_data)), measure=4:(ncol(obs_data)-2))
      names(student_obs)[[5]]<-"student"
    }
  }else{
    if(!activitycol){
      student_obs <- melt(obs_data, id=1:2, measure=3:(ncol(obs_data)-1))
      names(student_obs)[[3]]<-"student"
    }else{
      student_obs <- melt(obs_data, id=1:3, measure=4:(ncol(obs_data)-1))
      names(student_obs)[[4]]<-"student"
    }
  }
  student_obs$disengaged <- as.numeric(grepl(pattern = "disengaged", x = student_obs$value, fixed = TRUE))
  student_obs$looking <- as.numeric(grepl(pattern = "Looking", x = student_obs$value, fixed = TRUE))
  student_obs$talking <- as.numeric(grepl(pattern = "Talking", x = student_obs$value, fixed = TRUE))
  student_obs$technology <- as.numeric(grepl(pattern = "technology", x = student_obs$value, fixed = TRUE))
  student_obs$resources <- as.numeric(grepl(pattern = "resources", x = student_obs$value, fixed = TRUE))
  student_obs$external <- as.numeric(grepl(pattern = "external", x = student_obs$value, fixed = TRUE))
  student_obs$student.id <- paste(student_obs$group,student_obs$student)

  if(observercol){
    if(!activitycol){
      student_obs <- student_obs[,c(1:4,6:ncol(student_obs))]
    }else{
      student_obs <- student_obs[,c(1:5,7:ncol(student_obs))]
    }
  }else{
    if(!activitycol){
      student_obs <- student_obs[,c(1:3,5:ncol(student_obs))]
    }else{
      student_obs <- student_obs[,c(1:4,6:ncol(student_obs))]
    }
  }
  # summary(student_obs)
  
  student_obs$project <- project
  student_obs$date <- date

  student_obs$global.id <- paste(student_obs$project,student_obs$date,student_obs$student.id)
  
  student_obs  
}



# fit the MCA and project over live data?
# Data from previous days
df <- get(load("obsdata.Rdata"))
datamca <- df[,4:9]
for(i in 1:ncol(datamca)){
  datamca[,i] <- as.factor(datamca[,i])
}
res.mca <- MCA(datamca, graph = F)
df$engagement <-res.mca$ind$coord[,1]
df$offtask <- res.mca$ind$coord[,2]


```

Overall
=====================================  


    
Column 1 
-------------------------------------

### Observed engagement

```{r}

renderPlot({
  d <- ObD()
  data <- data.frame()
  if(nrow(d)!=0){
    data <- processObservationData(d, observercol = obscol)
  }
  if(nrow(data)>1){ # at least, two points to plot
    # Predict engagement and offtask fro the available data
    if(obscol){
      newdata <- data[,6:11]
    }else{
      newdata <- data[,5:10]
    }
    for(i in 1:ncol(newdata)){
      newdata[,i] <- as.factor(newdata[,i])
    }
    
    #To match factors, do mca on newdata and get the prediction data from the object, with olddata <- object$call$X[,rownames(object$var$eta),drop=FALSE]
    dummy.mca <- MCA(newdata, graph = F)
    newdata2 <- dummy.mca$call$X[,rownames(dummy.mca$var$eta),drop=FALSE]
    pred <- predict.MCA(res.mca, newdata2)
    data$engagement <- pred$coord[,1]
    data$offtask <- pred$coord[,2]
    
    data$time <- as.POSIXct(strptime(data$timestamp, "%d/%m/%Y %H:%M:%S"))
    data$timeofday <- as.POSIXct(strptime(paste(hour(data$time),
                                                minute(data$time),
                                                second(data$time), sep=":"),
                                          "%H:%M:%S"))

    ggplot(data, aes(x=timeofday, y=engagement, color=group))+
      geom_smooth(span=0.3, se=F)+
      geom_smooth(aes( group = 1 ), span=0.3, se=F, color="black", size=1.5) +
      #geom_smooth(method = "lm", formula = y ~ splines::bs(x, 3), se = FALSE)+
      #geom_smooth(method = "gam", formula = y ~ s(x, k=3), se = FALSE)+
      theme_minimal()+geom_point(alpha=0.2)+ggtitle("Engagement")

  }
  
})

```


Column 2 
-------------------------------------

### Engagement inequality 

(higher values may signal collaboration problems, e.g., only some group members engaged in the activity)

```{r}

renderPlot({
  d <- ObD()
  data <- data.frame()
  if(nrow(d)!=0){
    data <- processObservationData(d, observercol = obscol)
  }
  
  if(nrow(data)>1){ # at least, two points to plot
    # Predict engagement and offtask fro the available data
    if(obscol){
      newdata <- data[,6:11]
    }else{
      newdata <- data[,5:10]
    }
    for(i in 1:ncol(newdata)){
      newdata[,i] <- as.factor(newdata[,i])
    }
    
    #To match factors, do mca on newdata and get the prediction data from the object, with olddata <- object$call$X[,rownames(object$var$eta),drop=FALSE]
    dummy.mca <- MCA(newdata, graph = F)
    newdata2 <- dummy.mca$call$X[,rownames(dummy.mca$var$eta),drop=FALSE]
    pred <- predict.MCA(res.mca, newdata2)
    data$engagement <- pred$coord[,1]
    data$offtask <- pred$coord[,2]
    
    data$time <- as.POSIXct(strptime(data$timestamp, "%d/%m/%Y %H:%M:%S"))
    data$timeofday <- as.POSIXct(strptime(paste(hour(data$time),
                                                minute(data$time),
                                                second(data$time), sep=":"),
                                          "%H:%M:%S"))

    data$engagement2 <- data$engagement-min(data$engagement) # We make the values all positive
    bygroup.ineq <- aggregate(engagement2 ~ timeofday+group, data=data, Gini)
    ggplot(bygroup.ineq, aes(x=timeofday, y=engagement2, color=group))+
      theme_minimal()+
      geom_smooth(span=0.4, se=F)+
      geom_smooth(aes( group = 1 ), span=0.4, se=F, color="black", size=1.5) +
      #geom_smooth(method = "lm", formula = y ~ splines::bs(x, 3), se = FALSE)+
      #geom_smooth(method = "gam", formula = y ~ s(x, k=3), se = FALSE)+
      ggtitle("Inequality")+geom_point(alpha=0.2)+ylim(0,1)

    

  }
  
})

```


### Observations

```{r}
renderValueBox({
              d <- ObD()
              data <- data.frame()
              if(nrow(d)!=0){
                data <- processObservationData(d, observercol = F)
              }
              message="0 observations"
              if(nrow(data)>0){
                message <- paste(nrow(d),"obs. for",length(unique(data$group)),"groups")
                
              }
              valueBox(
                value=message,
                icon = "fa-microphone",
                color="primary")
                })

```
